[env:ttgo-t1]
platform = espressif32
board = ttgo-t1
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
lib_ldf_mode = deep
lib_deps = 
	codewitch-honey-crisis/htcw_uix
    codewitch-honey-crisis/htcw_esp_panel
    codewitch-honey-crisis/htcw_render_stats
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
    -Wall
    -Ofast
	-DTTGO_T1
upload_port = COM23 ; delete this line
monitor_port = COM23 ; delete this line

[env:m5stack-core2]
platform = espressif32
board = m5stack-core2
board_build.f_flash = 80000000L
board_build.flash_mode = qio
framework = espidf
upload_speed=921600
monitor_speed=115200
monitor_filters = esp32_exception_decoder
lib_deps = codewitch-honey-crisis/htcw_uix
            codewitch-honey-crisis/htcw_esp_panel
            codewitch-honey-crisis/htcw_render_stats
            codewitch-honey-crisis/htcw_esp_lcd_touch_ft6x36
            codewitch-honey-crisis/htcw_esp_lcd_panel_ili9342
            codewitch-honey-crisis/htcw_m5_stack_core2_power
build_flags= -DM5STACK_CORE2
    -Wall
    -Ofast
upload_port = COM8 ; delete this line
monitor_port = COM8 ; delete this line